# Generated by Django 5.1.1 on 2024-10-09 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=255)),
                ('about_descp1', models.TextField()),
                ('about_descp2', models.TextField()),
                ('about_list1', models.TextField()),
                ('about_list2', models.TextField()),
                ('about_list3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Callus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callus_title', models.CharField(max_length=255)),
                ('callus_descrpt', models.TextField()),
                ('callus_num', models.CharField(max_length=13)),
                ('callus_button_title', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_icon', models.ImageField(upload_to='', verbose_name='uploads/')),
                ('location', models.TextField()),
                ('email_icon', models.ImageField(upload_to='', verbose_name='uploads/')),
                ('email', models.EmailField(max_length=254)),
                ('phone_icon', models.ImageField(upload_to='', verbose_name='uploads/')),
                ('phone_num', models.CharField(max_length=13)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_subject', models.CharField(max_length=100)),
                ('client_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('data_delay', models.IntegerField()),
                ('faq_listid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Helpers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_name', models.CharField(max_length=255)),
                ('helper_age', models.TextField()),
                ('helper_designation', models.TextField()),
                ('filter_designation', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='')),
                ('heading', models.CharField(max_length=255)),
                ('intro_descp', models.CharField(max_length=255)),
                ('background_img', models.ImageField(upload_to='')),
                ('newsletter_title', models.CharField(max_length=255)),
                ('newsletter_decrpt', models.TextField()),
                ('taskease_phone', models.CharField(max_length=13)),
                ('taskease_email', models.EmailField(max_length=254)),
                ('service_descrpt', models.TextField()),
                ('whyus_background_img', models.ImageField(upload_to='')),
                ('helpers_title', models.CharField(max_length=255)),
                ('hiringform_title', models.CharField(max_length=255)),
                ('contact_title', models.CharField(max_length=255)),
                ('faq_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Whyus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whyus_question', models.TextField()),
                ('whyus_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hiringform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('home_address', models.TextField()),
                ('phone', models.CharField(max_length=13)),
                ('helper_name', models.TextField()),
                ('helper_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpers', to='Taskease_app.helpers')),
            ],
        ),
    ]
