# Generated by Django 5.1.1 on 2024-10-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_icon_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
