# Generated by Django 5.1.1 on 2024-10-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0002_service_service_icon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpers',
            name='helper_image',
            field=models.ImageField(default='default', upload_to=''),
            preserve_default=False,
        ),
    ]
