# Generated by Django 5.1.1 on 2024-10-09 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0003_helpers_helper_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_icon',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location_icon',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_icon',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='setting',
            name='location',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='location_icon',
            field=models.ImageField(default='default', upload_to='', verbose_name='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='taskease_email_icon',
            field=models.ImageField(default=123, upload_to='', verbose_name='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='taskease_phone_icon',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='', verbose_name='uploads/'),
            preserve_default=False,
        ),
    ]
