# Generated by Django 5.1.1 on 2024-10-09 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0004_remove_contact_email_remove_contact_email_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='location_icon',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='taskease_email_icon',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='taskease_phone_icon',
        ),
        migrations.AddField(
            model_name='setting',
            name='email_icon_name',
            field=models.CharField(default='default', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='location_icon_name',
            field=models.CharField(default='default', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='phone_icon_name',
            field=models.CharField(default='default', max_length=13),
            preserve_default=False,
        ),
    ]
