# Generated by Django 5.1.1 on 2024-10-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0005_remove_setting_location_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='location_map',
            field=models.TextField(default='https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d12097.433213460943!2d-74.0062269!3d40.7101282!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb89d1fe6bc499443!2sDowntown+Conference+Center!5e0!3m2!1smk!2sbg!4v1539943755621'),
            preserve_default=False,
        ),
    ]
