# Generated by Django 5.1.1 on 2024-10-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0006_setting_location_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='services_title',
            field=models.CharField(default='Services', max_length=255),
            preserve_default=False,
        ),
    ]
