# Generated by Django 5.1.1 on 2024-10-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0007_setting_services_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiringform',
            name='helper_name',
        ),
    ]
