# Generated by Django 5.1.1 on 2024-10-13 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0012_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
