# Generated by Django 5.1.1 on 2024-10-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
