# Generated by Django 5.1.1 on 2025-01-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0017_alter_profile_image_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
