# Generated by Django 5.1.1 on 2025-03-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskease_app', '0018_delete_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpers',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='helpers',
            name='location',
            field=models.CharField(default='Not Specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='helpers',
            name='helper_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='helpers',
            name='helper_designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='helpers',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
